---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: posts
  label: Blog
  create: documents
  match: "**/*"
  new_doc_ext: md
  templates:
  - post
upload_dir: personal/blog/images
public_path: https://res.cloudinary.com/chuck-huey/image/upload
front_matter_path: ''
use_front_matter_path: 
file_template: ":filename:"
build:
  preview_output_directory: ".next"
  install_dependencies_command: yarn
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: yarn dev
